version: "3.8"

services:
  # nextjs_prod:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.prod
  #     # target: production
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   # command: ["/bin/sleep", "3600"]
  #   environment:
  #     DATABASE_URL: "postgresql://postgres:password@db:5432/postgres"
  #     JWT_SECRET: "your_jwt_secret"
  #     JWT_EXPIRATION_TIME: "48h"
  #     
  #     BASE_URL: "http://localhost:3000"
  #   restart: unless-stopped

  db:
    image: postgres
    ports:
      - "5432:5432"
    container_name: travelblog_drizzle_db
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
