version: "3.8"

services:
  nextjs_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
      # target: production
    ports:
      - "3001:3000"
    depends_on:
      - db
    # command: ["/bin/sleep", "3600"]
    restart: unless-stopped

  db:
    image: postgres
    ports:
      - "5433:5432"
    container_name: travelblog_drizzle_db
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
